# Generated by Django 2.0.5 on 2018-07-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10, null=True)),
                ('last_name', models.CharField(max_length=10, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('Setor', models.CharField(max_length=30, null=True)),
                ('Gestor', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('funcao', models.CharField(max_length=30, null=True)),
                ('num_tel', models.CharField(max_length=30, null=True)),
                ('image', models.FileField(null=True, upload_to='documents/')),
                ('perm', models.CharField(choices=[('SIG', 'SIG'), ('HSE', 'HSE'), ('POR', 'PORTARIA')], default='SIG', max_length=3, null=True)),
            ],
            options={
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
