# Generated by Django 2.0.5 on 2018-07-17 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cad_resp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_resp', models.CharField(max_length=30)),
                ('empresa_resp', models.CharField(max_length=30)),
                ('funcao_resp', models.CharField(max_length=30)),
                ('telefone_resp', models.CharField(blank=True, max_length=30)),
                ('email_resp', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('txt1', models.CharField(max_length=30)),
                ('txt2', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('toolTip', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='docs_integracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade_documento', models.DateField()),
                ('arquivo', models.FileField(upload_to='documents/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_documento', models.CharField(max_length=100)),
                ('validade_documento', models.CharField(max_length=30)),
                ('arquivo_documento', models.FileField(upload_to='documents/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('enviado', models.BooleanField(default=False)),
                ('hse', models.CharField(default='AG', max_length=2)),
                ('emp', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='empresa_terc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('usuario', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=20)),
                ('status', models.CharField(default='AG', max_length=10)),
                ('funcao', models.CharField(max_length=100)),
                ('data_int', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa_terc')),
                ('resp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cad_resp')),
            ],
        ),
        migrations.CreateModel(
            name='Solic_cad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Solicitante', models.CharField(max_length=100)),
                ('Contato', models.CharField(max_length=100)),
                ('Obs', models.CharField(max_length=1000)),
            ],
        ),
    ]
