# Generated by Django 2.0.5 on 2018-07-17 04:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aux_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cham', models.IntegerField()),
                ('tps', models.CharField(max_length=100)),
                ('colab', models.CharField(max_length=100)),
                ('id_col', models.CharField(max_length=55)),
                ('status', models.CharField(default='AG', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='chamado_hse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=100)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('tempo_estimado', models.CharField(max_length=100)),
                ('nome_proj', models.CharField(max_length=100)),
                ('setor_solicitante', models.CharField(max_length=100)),
                ('gestor_solicitante', models.CharField(max_length=100)),
                ('tipo_servico', models.CharField(blank=True, max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=1000)),
                ('email_terc', models.CharField(max_length=500)),
                ('email_solicitante', models.CharField(max_length=100)),
                ('fone_solicitante', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('data', models.DateField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.empresa_terc')),
            ],
        ),
        migrations.CreateModel(
            name='Hse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cham', models.CharField(max_length=100)),
                ('ator', models.CharField(max_length=100)),
                ('acao', models.CharField(max_length=10000)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cham', models.CharField(max_length=100)),
                ('ator', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=10000)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.CharField(default=None, max_length=10)),
                ('id_col', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='portaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(default=None, max_length=10)),
            ],
        ),
    ]
