# Generated by Django 2.0.5 on 2018-07-17 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('Hse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado_hse',
            name='resp_terc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cad_resp'),
        ),
    ]
