# Generated by Django 2.0.5 on 2018-07-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hse', '0003_auto_20180717_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado_hse',
            name='resp_terc',
            field=models.CharField(max_length=100),
        ),
    ]
